name: graphgps
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - rdkit
  - openbabel
  - fsspec
  - pip
  - pip:
      - torch==2.5.1
      - torchvision
      - torchaudio
      - torch-geometric
      - pytorch-lightning
      - hyper-connections
      - torch-einops-utils
      - yacs
      - torchmetrics
      - performer-pytorch
      - tensorboardX
      - ogb
      - wandb
      - scikit-learn<1.6.0
      - networkx
      - GraphRicciCurvature
      - POT
      - torch_scatter -f https://data.pyg.org/whl/torch-2.5.1+cpu.html
      - torch_sparse -f https://data.pyg.org/whl/torch-2.5.1+cpu.html
      - torch_cluster -f https://data.pyg.org/whl/torch-2.5.1+cpu.html
      - torch_spline_conv -f https://data.pyg.org/whl/torch-2.5.1+cpu.html
